#spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
server:
 port: 8080

spring:
  liquibase:
    enabled: true

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/world1?createDatabaseIfNotExist=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:0085}

    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
   database-platform: org.hibernate.dialect.MySQL8Dialect
   hibernate:
     ddl-auto: validate
   generate-ddl: true
   database: mysql
   show-sql: true

